import { ToolDefinition } from "@/lib/types";

const defaultFaqs = (title: string) => [
  {
    question: `Is ${title} free on PDF World?`,
    answer:
      "Yes. PDF World provides a free online workflow for this tool with no signup required.",
  },
  {
    question: "Are my files stored permanently?",
    answer:
      "No. Files are processed in-memory and cleared after completion to support zero-persistence handling.",
  },
  {
    question: `Can I use ${title} without signup?`,
    answer:
      "Yes. You can upload, process, and download files directly in your browser without creating an account.",
  },
];

const defaultSteps = (title: string) => [
  `Upload your file(s) for ${title}.`,
  "Adjust options based on your desired output quality.",
  "Start processing and wait a few seconds.",
  "Download the final file securely to your device.",
];

const define = (
  tool: Omit<ToolDefinition, "howToSteps" | "faqs"> &
    Partial<Pick<ToolDefinition, "howToSteps" | "faqs">>,
): ToolDefinition => ({
  ...tool,
  howToSteps: tool.howToSteps ?? defaultSteps(tool.title),
  faqs: tool.faqs ?? defaultFaqs(tool.title),
});

export const tools: ToolDefinition[] = [
  define({
    slug: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDF files into one document in seconds.",
    category: "Organize",
    icon: "Combine",
    keywords: ["merge pdf", "combine pdf", "free", "online", "no signup", "fast"],
  }),
  define({
    slug: "split-pdf",
    title: "Split PDF",
    description: "Split one PDF into multiple files by page range.",
    category: "Organize",
    icon: "Scissors",
    keywords: ["split pdf", "extract ranges", "online", "free", "no signup"],
  }),
  define({
    slug: "remove-pages",
    title: "Remove Pages",
    description: "Delete unwanted pages from PDF documents quickly.",
    category: "Organize",
    icon: "Trash2",
    keywords: ["remove pdf pages", "delete pages", "fast", "online"],
  }),
  define({
    slug: "extract-pages",
    title: "Extract Pages",
    description: "Extract selected pages into a new PDF file.",
    category: "Organize",
    icon: "FileOutput",
    keywords: ["extract pdf pages", "new pdf", "free", "no signup"],
  }),
  define({
    slug: "organize-pages",
    title: "Organize Pages",
    description: "Reorder and arrange pages for a cleaner PDF structure.",
    category: "Organize",
    icon: "PanelsTopLeft",
    keywords: ["organize pdf", "reorder pages", "drag and drop"],
  }),
  define({
    slug: "scan-to-pdf",
    title: "Scan to PDF",
    description: "Convert scanned documents into optimized PDF files.",
    category: "Organize",
    icon: "ScanSearch",
    keywords: ["scan to pdf", "document scanner", "online"],
  }),
  define({
    slug: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate all or selected pages to the correct orientation.",
    category: "Organize",
    icon: "RotateCw",
    keywords: ["rotate pdf", "fix orientation", "free"],
  }),
  define({
    slug: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert DOC and DOCX files to high-quality PDF.",
    category: "Convert To PDF",
    icon: "FileText",
    keywords: ["word to pdf", "docx to pdf", "free online converter"],
  }),
  define({
    slug: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert spreadsheets to print-ready PDF files.",
    category: "Convert To PDF",
    icon: "Sheet",
    keywords: ["excel to pdf", "xlsx to pdf", "fast converter"],
  }),
  define({
    slug: "ppt-to-pdf",
    title: "PPT to PDF",
    description: "Transform PowerPoint decks into polished PDFs.",
    category: "Convert To PDF",
    icon: "Presentation",
    keywords: ["ppt to pdf", "powerpoint to pdf", "free"],
  }),
  define({
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert JPG images into compact PDF documents.",
    category: "Convert To PDF",
    icon: "Image",
    keywords: ["jpg to pdf", "image to pdf", "online"],
  }),
  define({
    slug: "png-to-pdf",
    title: "PNG to PDF",
    description: "Turn PNG image files into secure PDF output.",
    category: "Convert To PDF",
    icon: "ImagePlus",
    keywords: ["png to pdf", "convert image", "free"],
  }),
  define({
    slug: "bmp-to-pdf",
    title: "BMP to PDF",
    description: "Convert BMP image files to downloadable PDFs.",
    category: "Convert To PDF",
    icon: "FileImage",
    keywords: ["bmp to pdf", "online converter", "no signup"],
  }),
  define({
    slug: "tiff-to-pdf",
    title: "TIFF to PDF",
    description: "Convert TIFF scans and image sets into PDF.",
    category: "Convert To PDF",
    icon: "Images",
    keywords: ["tiff to pdf", "scan to pdf", "fast"],
  }),
  define({
    slug: "txt-to-pdf",
    title: "TXT to PDF",
    description: "Convert plain text files into styled PDF format.",
    category: "Convert To PDF",
    icon: "NotebookPen",
    keywords: ["txt to pdf", "text to pdf", "free online"],
  }),
  define({
    slug: "rtf-to-pdf",
    title: "RTF to PDF",
    description: "Convert rich text files to universal PDF documents.",
    category: "Convert To PDF",
    icon: "FilePen",
    keywords: ["rtf to pdf", "rich text converter", "no signup"],
  }),
  define({
    slug: "odt-to-pdf",
    title: "ODT to PDF",
    description: "Convert OpenDocument text files to PDF format.",
    category: "Convert To PDF",
    icon: "FileType2",
    keywords: ["odt to pdf", "openoffice converter", "free"],
  }),
  define({
    slug: "html-to-pdf",
    title: "HTML to PDF",
    description: "Render HTML pages and snippets into clean PDFs.",
    category: "Convert To PDF",
    icon: "CodeXml",
    keywords: ["html to pdf", "webpage to pdf", "fast online"],
  }),
  define({
    slug: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDFs into editable DOCX format.",
    category: "Convert From PDF",
    icon: "FileType",
    keywords: ["pdf to word", "editable doc", "free"],
  }),
  define({
    slug: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract table data from PDF to spreadsheet format.",
    category: "Convert From PDF",
    icon: "Table2",
    keywords: ["pdf to excel", "table extraction", "online"],
  }),
  define({
    slug: "pdf-to-ppt",
    title: "PDF to PPT",
    description: "Convert PDF pages into presentation slides.",
    category: "Convert From PDF",
    icon: "MonitorPlay",
    keywords: ["pdf to ppt", "pdf to powerpoint", "fast"],
  }),
  define({
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Export PDF pages as JPG image files.",
    category: "Convert From PDF",
    icon: "FileImage",
    keywords: ["pdf to jpg", "extract images", "free"],
  }),
  define({
    slug: "pdf-to-png",
    title: "PDF to PNG",
    description: "Convert each page of your PDF into PNG files.",
    category: "Convert From PDF",
    icon: "ImageDown",
    keywords: ["pdf to png", "online converter", "no signup"],
  }),
  define({
    slug: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    description: "Convert standard PDFs to archive-ready PDF/A.",
    category: "Convert From PDF",
    icon: "Archive",
    keywords: ["pdf to pdfa", "archive pdf", "compliance"],
  }),
  define({
    slug: "pdf-to-text",
    title: "PDF to Text",
    description: "Extract plain text content from PDF documents.",
    category: "Convert From PDF",
    icon: "TextSearch",
    keywords: ["pdf to text", "extract text", "free online"],
  }),
  define({
    slug: "compress-pdf",
    title: "Compress PDF",
    description: "Shrink PDF file size with low, medium, and high compression levels.",
    category: "Optimize & Edit",
    icon: "Gauge",
    keywords: ["compress pdf", "reduce file size", "3 levels"],
  }),
  define({
    slug: "repair-pdf",
    title: "Repair PDF",
    description: "Fix corrupted PDF structures and recover readable content.",
    category: "Optimize & Edit",
    icon: "Wrench",
    keywords: ["repair pdf", "fix broken pdf", "online"],
  }),
  define({
    slug: "ocr-pdf",
    title: "OCR PDF",
    description: "Recognize text from scanned PDFs for searchable output.",
    category: "Optimize & Edit",
    icon: "ScanText",
    keywords: ["ocr pdf", "text recognition", "scanned pdf"],
  }),
  define({
    slug: "edit-pdf",
    title: "Edit PDF",
    description: "Edit text, images, and layout blocks inside PDF files.",
    category: "Optimize & Edit",
    icon: "PencilRuler",
    keywords: ["edit pdf", "modify pdf", "fast"],
  }),
  define({
    slug: "pdf-annotator",
    title: "PDF Annotator",
    description: "Add comments, highlights, and drawing annotations.",
    category: "Optimize & Edit",
    icon: "Highlighter",
    keywords: ["annotate pdf", "highlight pdf", "online"],
  }),
  define({
    slug: "pdf-reader",
    title: "PDF Reader",
    description: "Open, preview, and navigate PDF files quickly in-browser.",
    category: "Optimize & Edit",
    icon: "BookOpenText",
    keywords: ["pdf reader", "view pdf", "free"],
  }),
  define({
    slug: "crop-pdf",
    title: "Crop PDF",
    description: "Trim page margins and focus only on essential content.",
    category: "Optimize & Edit",
    icon: "Crop",
    keywords: ["crop pdf", "trim margins", "online"],
  }),
  define({
    slug: "sign-pdf",
    title: "Sign Pages",
    description: "Add signature text to selected PDF pages quickly.",
    category: "Security & Signs",
    icon: "Signature",
    keywords: ["sign pages", "sign pdf", "signature", "no signup"],
  }),
  define({
    slug: "add-watermark",
    title: "Add Watermark",
    description: "Stamp text or logo watermarks across PDF pages.",
    category: "Security & Signs",
    icon: "Stamp",
    keywords: ["watermark pdf", "logo watermark", "branding"],
  }),
  define({
    slug: "number-pages",
    title: "Number Pages",
    description: "Insert page numbers with custom style and positions.",
    category: "Security & Signs",
    icon: "ListOrdered",
    keywords: ["number pages pdf", "page numbering", "free"],
  }),
];

export const toolBySlug = Object.fromEntries(
  tools.map((tool) => [tool.slug, tool]),
) as Record<string, ToolDefinition>;

export const categories = Array.from(new Set(tools.map((tool) => tool.category)));
